### ISSUE TITLE
On s'emMERDE bien

### ISSUE THREAD

**Issue by RobinPetit** [AntoinePassemiers/Jerry-The-Race-Car-Driver#1]
J'ai testé le projet. J'ai fait mon propre PSO pour fonctionner de la même manière. Et y a pas à dire... On s'emMERDE bien !

**Comment by AntoinePassemiers** [comment]
J'ai mis ce dépôt en public parce que je tenais à partager mon ennui profond avec vous. Je tiens à m'excuser auprès de toute ma communauté.
